name: Main Deploy

on:
  push:
    branches:
      - main

jobs:
  main-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Main environment
        run: |
          echo "Deploying to Main environment 8.1 ..."
          # Your main environment commands go here
