name: Deploy Only If Tag Is On Upgrading

on:
  push:
    # Trigger for any tag push
    tags:
      - "*"

jobs:
  production:
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Ensure commit is on upgrading
        run: |
          # Replace `true` with your actual check, e.g.:
          # if git branch --contains HEAD | grep -q upgrading; then
          if git branch --contains HEAD | grep -q "upgrading"; then
            echo "Commit is on upgrading, proceeding..."
          else
            echo "Commit is not on upgrading, exiting..."
            exit 1
          fi

      - run: echo "Upgrading run successfully"
