
name: Deploy to Production
# Controls when the workflow will run
on:
  push:
    # branches: ["main"]
    tags:        
      - '*' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  production:
    steps:
      run: |
        # "main" must appear in the list of branches containing HEAD
        if git branch --contains HEAD | grep -q "main"; then
          echo "Tag's commit is on main — proceeding..."
        else
          echo "Tag's commit is NOT on main — exiting."
          exit 1
        - run: |
            echo Production run successfully