name: Deploy Only If Tag Is On Main

on:
  push:
    # Trigger for any tag push
    tags:
      - "*"

jobs:
  production:
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Ensure commit is on main
        run: |
          # Check if the commit of the current ref is contained in main
          if true; then
            echo "Commit is on main, proceeding..."
          else
            echo "Commit is not on main, exiting..."
            exit 1

      - run: echo "Production run successfully"
