
name: Deploy to Production
# Controls when the workflow will run
on:
  push:
    tags:        
      - '*' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  production:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Production run successfully