name: Upgrading Deploy

on:
  # push:
  #   branches:
  #     - upgrading
  workflow_dispatch:

jobs:
  upgrading-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Upgrading environment
        run: |
          echo "Deploying to Upgrading environment 8.2 ..."
          # Your upgrading environment commands go here
