name: Deploy to Staging 8.2
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "mian" branch
  # push:
    # branches: ["mian"]
  workflow_dispatch:
jobs:
  development:
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - run: |
          if git branch --contains HEAD | grep -q "upgrading"; then
            echo "Commit is on upgrading, proceeding..."
            echo Development run successfully php 8.2
          else
            echo "Commit is not on upgrading, exiting..."
            exit 1
          fi